### ISSUE TITLE
[BUG] Error on Colab

### ISSUE THREAD

**Issue by AishwaryaVerma** [robustness-gym/robustness-gym#11] opened 2021-02-09 04:39 UTC
**Describe the bug**
After installing robustness gym via pip, the library gave cytoolz.itertoolz error

**To Reproduce**

1. Code snippet '....'
import robustnessgym as rg 

2. Instructions (Run '...')
3. Errors and traceback '....'
---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-49-59b142487667> in <module>()
----> 1 import robustnessgym as rg
      2 
      3 # Load the boolq data
      4 dataset = rg.Dataset.load_dataset('boolq', split='train[:10]')
      5 

3 frames

/usr/local/lib/python3.8/site-packages/robustnessgym/__init__.py in <module>()
      1 """Import common classes."""
      2 # flake8: noqa
----> 3 from robustnessgym.cachedops.allen.allen_predictor import AllenPredictor
      4 from robustnessgym.cachedops.allen.constituency_parser import AllenConstituencyParser
      5 from robustnessgym.cachedops.allen.dependency_parser import AllenDependencyParser

/usr/local/lib/python3.8/site-packages/robustnessgym/cachedops/__init__.py in <module>()
     12 # from .spacy.spacy import Spacy
     13 # from .textblob.textblob import TextBlob
---> 14 from .spacy import Spacy  # noqa
     15 from .stanza import Stanza  # noqa
     16 from .textblob import TextBlob  # noqa

/usr/local/lib/python3.8/site-packages/robustnessgym/cachedops/spacy.py in <module>()
      3 from typing import List
      4 
----> 5 import cytoolz as tz
      6 import spacy
      7 import torch

/usr/local/lib/python3.8/site-packages/cytoolz/__init__.py in <module>()
----> 1 from .itertoolz import *
      2 
      3 from .functoolz import *
      4 
      5 from .dicttoolz import *

ModuleNotFoundError: No module named 'cytoolz.itertoolz'

**System Information**
 - Colab Notebook, Linux 18.04.5 LTS
 - Versions for RG and relevant dependencies [e.g. `robustnessgym` (v0.0.2), `spacy` (v2.3.5)]
 - Python 3.8.5

**Comment by krandiash** [comment] 2021-02-09 08:22
Thanks for reporting!

This is likely an issue caused by the Colab runtime. Could you try running `pip install cytoolz` as a sanity check (it should be installed already)? If that doesn't help, would you mind sharing a link to a minimal Colab notebook that we can use to debug what might be happening?

**Comment by AishwaryaVerma** [comment] 2021-02-09 08:40
> 
> 
> Thanks for reporting!
> 
> This is likely an issue caused by the Colab runtime. Could you try running `pip install cytoolz` as a sanity check (it should be installed already)? If that doesn't help, would you mind sharing a link to a minimal Colab notebook that we can use to debug what might be happening?

I already tried by installing cytoolz, but still the problem persists. I am sharing a link to colab notebook. 

https://colab.research.google.com/drive/12pyzutS5smqvVqMN04hut5pgxhhPGnB_?usp=sharing

Thank you.

**Comment by krandiash** [comment] 2021-02-11 04:28
I wasn't able to find a clear fix on the RG end, I suspect this is to do with the Colab runtime (and perhaps Cython) unfortunately. 

My recommendation would be to try to use a standard Jupyter notebook if possible. On our end, we'll try to ease some of the dependencies (around cytoolz and Python 3.8) in our next release (coming in ~3 weeks). I'll let you know when that's fixed.

Closing this for now, thanks for reporting!

**Closed by krandiash** 2021-02-11 04:28 UTC

**Comment by AishwaryaVerma** [comment] 2021-02-12 05:13
> 
> 
> I wasn't able to find a clear fix on the RG end, I suspect this is to do with the Colab runtime (and perhaps Cython) unfortunately.
> 
> My recommendation would be to try to use a standard Jupyter notebook if possible. On our end, we'll try to ease some of the dependencies (around cytoolz and Python 3.8) in our next release (coming in ~3 weeks). I'll let you know when that's fixed.
> 
> Closing this for now, thanks for reporting!

Okay. Thanks.
